services:
  citrineos-ocpi:
    image: ghcr.io/tinkerve/rexharge-citrineos-ocpi:latest
    deploy:
      labels:
        # HTTP API Swagger UI
        - traefik.enable=true
        - traefik.http.routers.citrine-ocpi.service=citrine-ocpi
        - traefik.http.routers.citrine-ocpi.entrypoints=websecure
        - traefik.http.routers.citrine-ocpi.rule=Host(`citrine-ocpi.staging-app.rexharge.net`)
        - traefik.http.routers.citrine-ocpi.tls.certresolver=leresolver
        - traefik.http.services.citrine-ocpi.loadbalancer.server.port=8085
    environment:
      APP_NAME: 'all'
      APP_ENV: 'docker'
      DB_HOST: ${DOCKER_DATABASE_HOST}
      DB_USER: ${DOCKER_DATABASE_USERNAME}
      DB_PASS: ${DOCKER_DATABASE_PASSWORD}
      AMQP_URL: ${DOCKER_RABBITMQ_URL}
      HASURA_GRAPHQL_ENDPOINT: ${DOCKER_HASURA_GRAPHQL_ENDPOINT}
      HASURA_GRAPHQL_ADMIN_SECRET: ${DOCKER_HASURA_GRAPHQL_ADMIN_SECRET}
      AMQP_EXCHANGE: 'citrineos'
    networks:
      - rexharge_network
      - traefik_proxy

networks:
  rexharge_network:
    external: true
  traefik_proxy:
    external: true
