services:
  citrineos-ocpi:
    build:
      context: ../
      dockerfile: ./Server/deploy.Dockerfile
    deploy:
      labels:
        # HTTP API Swagger UI
        - traefik.enable=true
        - traefik.http.routers.citrine-ocpi.service=citrine-ocpi
        - traefik.http.routers.citrine-ocpi.entrypoints=websecure
        - traefik.http.routers.citrine-ocpi.rule=Host(`citrine-ocpi.staging-app.rexharge.net`)
        - traefik.http.routers.citrine-ocpi.tls.certresolver=leresolver
        - traefik.http.services.citrine-ocpi.loadbalancer.server.port=8080
    environment:
      APP_NAME: 'all'
      APP_ENV: 'docker'
      DB_HOST: ${DOCKER_DATABASE_HOST}
      AMQP_URL: ${DOCKER_RABBITMQ_URL}
      AMQP_EXCHANGE: 'citrineos'
    networks:
      - rexharge_network
      - traefik_proxy

networks:
  rexharge_network:
    external: true
  traefik_proxy:
    external: true

