# SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
#
# SPDX-License-Identifier: Apache-2.0

services:
  citrineos-ocpi:
    build:
      context: ../
      dockerfile: ./Server/deploy.Dockerfile
    environment:
      APP_NAME: "all"
      APP_ENV: "docker"
      DB_HOST: "ocpp-db"
      AMQP_URL: "amqp://guest:guest@amqp-broker:5672"
      AMQP_EXCHANGE: "citrineos"
    ports:
      - 8085:8085
